'use client'
import { useState, useEffect } from 'react'

const C = {
  ink:'#15302A', green:'#0E6B4F', greenDeep:'#0A5440', greenSoft:'#E3EFE8',
  ivory:'#F5EFE3', sand:'#EDE4D2', gold:'#D99A2B', goldSoft:'#F4E2BC',
  amber:'#E0A23B', mute:'#6E7F76', line:'#E7DECC', card:'#FFFFFF',
}
const display = "'Fraunces', Georgia, serif"
const ui      = "'Plus Jakarta Sans', system-ui, sans-serif"

const T = {
  en: {
    nav_gov:'For Governments', nav_ind:'For Individuals', nav_par:'For Partners', nav_contact:'Contact',
    nav_login:'Log in', nav_cta:'Become a partner',
    eyebrow:'For healthcare partners',
    h1:"Join Africa's ", h1_accent:'healthcare grid.',
    lede:'Clinics, pharmacies, doctors, employers, and delivery providers join the Klinova network and receive verified patient referrals.',
    cta1:'Apply to be a partner', cta2:'Talk to our team',
    tr1:'No setup fee for pilot partners', tr2:'Instant patient referrals', tr3:'Revenue share model',
    pt_ey:'Partner types', pt_h:"Whether you have a clinic, pharmacy, lab, or motorbike, there's a place for you.",
    p1h:'Clinics & hospitals', p1p:'Receive pre-triaged patient referrals ready for in-person care. Digital patient dossiers arrive before they walk in the door.', p1t:'Referrals + dashboard',
    p2h:'Pharmacies', p2p:'Receive digital prescriptions directly from Klinova doctors. Zero paper, instant notification, faster dispensing.', p2t:'Digital Rx + delivery',
    p3h:'Doctors & nurses', p3p:'Consult patients by chat, voice, or video on your own schedule. Klinova handles triage, records, and payment.', p3t:'Teleconsult income',
    p4h:'Delivery & transport', p4p:'Deliver medications from partner pharmacies to patients. Join the network and receive steady, verified delivery requests.', p4t:'Last-mile delivery',
    dash_ey:'Clinic partner dashboard', dash_h:'Everything your clinic needs, in one place.',
    dash_sub:"Klinova's partner dashboard is built around how clinics actually work: appointments, referrals, prescriptions, and performance, all in one screen.",
    m1h:'Patient referral queue', m1p:'See incoming Klinova referrals in real time. Accept or reschedule with one click. Patient dossier attached.',
    m2h:'Appointment management', m2p:'Full booking calendar linked to your actual capacity. Patients see your real-time availability.',
    m3h:'Digital health records', m3p:'Access patient history, prior consults, and prescriptions. No clipboard, no paper.',
    m4h:'Pharmacy & Rx module', m4p:'Issue digital prescriptions that route automatically to the nearest partner pharmacy.',
    m5h:'Analytics & reporting', m5p:'Track consultations, referrals, revenue, and patient outcomes by day, week, or month.',
    m6h:'Payments & billing', m6p:'Klinova handles patient billing and sends your share within 48 hours of each consultation.',
    dash_title:'Clinic overview', dash_ref:'Referrals today', dash_rev:'Revenue this month', dash_wait:'Avg. patient wait', dash_rx:'Pending Rx to fill',
    rev_ey:'Revenue model', rev_h:'You get paid. We grow together.',
    rev_sub:'Klinova partners earn revenue on every referral and consultation routed through the platform.',
    r1h:'80%', r1l:'Consultation revenue to clinics', r1p:'For every in-clinic visit generated by a Klinova referral, your clinic keeps 80% of the consultation fee.',
    r2h:'100%', r2l:'Prescription revenue to pharmacies', r2p:'You keep full prescription revenue. Klinova earns only a small dispatch fee for routing the prescription to you.',
    r3h:'48h', r3l:'Payment settlement', r3p:'Revenue is settled to your mobile money or bank account within 48 hours of each transaction. No waiting.',
    join_ey:'How to join', join_h:'Onboard in three steps.',
    j1h:'Apply online', j1p:'Fill in the pilot partner form below. Tell us your partner type, location, and capacity. Takes under five minutes.',
    j2h:'Get verified', j2p:'Our team verifies your license, location, and readiness. We typically respond within 3 business days.',
    j3h:'Go live', j3p:"You're added to the Klinova network. Patients and referrals start flowing immediately. Your dashboard is live.",
    app_ey:'Pilot partner program', app_h:'Join our pilot. No setup fee.',
    app_p:"We're expanding our partner network across Togo, Ghana, Benin, and Côte d'Ivoire. Pilot partners are onboarded free of charge and work directly with our team.",
    b1:'No setup fee for pilot partners', b2:'Dedicated onboarding support', b3:'Co-marketing to our patient network', b4:'Early access to new features', b5:'Influence the product roadmap',
    form_title:'Partner application', f1:'Organization name', f2:'Partner type', f3:'Country', f4:'Your name', f5:'Contact email',
    sel_type:'Select type…', opt_clinic:'Clinic / Hospital', opt_pharma:'Pharmacy', opt_doc:'Doctor / Nurse (individual)', opt_lab:'Lab / Diagnostic centre', opt_del:'Delivery / Transport',
    sel_country:'Select country…', opt_other:'Other',
    submit:'Submit application', form_note:'We respond within 3 business days.',
    ft_blurb:'The Invisible Grid powering African healthcare. Lomé, Togo.', ft_tag:'Born in Africa. Built for Life.',
    ft_product:'Product', ft_partners:'Partners', ft_company:'Company', ft_copy:'© 2026 Klinova. All rights reserved.',
  },
  fr: {
    nav_gov:'Pour les gouvernements', nav_ind:'Pour les individus', nav_par:'Pour les partenaires', nav_contact:'Contact',
    nav_login:'Connexion', nav_cta:'Devenir partenaire',
    eyebrow:'Pour les partenaires de santé',
    h1:"Rejoignez la grille de santé ", h1_accent:"de l'Afrique.",
    lede:'Cliniques, pharmacies, médecins, employeurs et prestataires de livraison rejoignent le réseau Klinova et reçoivent des références de patients vérifiées.',
    cta1:'Postuler comme partenaire', cta2:'Parler à notre équipe',
    tr1:'Pas de frais de configuration pour les partenaires pilotes', tr2:'Références patients instantanées', tr3:'Modèle de partage des revenus',
    pt_ey:'Types de partenaires', pt_h:"Que vous ayez une clinique, une pharmacie, un labo ou une moto, il y a une place pour vous.",
    p1h:'Cliniques & hôpitaux', p1p:'Recevez des références de patients pré-triés prêts pour des soins en personne. Les dossiers numériques des patients arrivent avant qu\'ils franchissent la porte.', p1t:'Références + tableau de bord',
    p2h:'Pharmacies', p2p:'Recevez des ordonnances numériques directement des médecins Klinova. Zéro papier, notification instantanée, distribution plus rapide.', p2t:'Rx numérique + livraison',
    p3h:'Médecins & infirmiers', p3p:'Consultez les patients par chat, voix ou vidéo selon votre propre horaire. Klinova gère le triage, les dossiers et le paiement.', p3t:'Revenus de téléconsultation',
    p4h:'Livraison & transport', p4p:'Livrez les médicaments des pharmacies partenaires aux patients. Rejoignez le réseau et recevez des demandes de livraison régulières et vérifiées.', p4t:'Livraison du dernier kilomètre',
    dash_ey:'Tableau de bord partenaire clinique', dash_h:'Tout ce dont votre clinique a besoin, en un seul endroit.',
    dash_sub:"Le tableau de bord partenaire de Klinova est conçu autour du fonctionnement réel des cliniques : rendez-vous, références, ordonnances et performance, tout sur un seul écran.",
    m1h:'File d\'attente de références patients', m1p:'Consultez les références Klinova entrantes en temps réel. Acceptez ou reprogrammez en un clic. Dossier patient joint.',
    m2h:'Gestion des rendez-vous', m2p:'Calendrier de réservation complet lié à votre capacité réelle. Les patients voient votre disponibilité en temps réel.',
    m3h:'Dossiers de santé numériques', m3p:'Accédez à l\'historique des patients, aux consultations précédentes et aux ordonnances. Sans presse-papiers, sans papier.',
    m4h:'Module pharmacie & Rx', m4p:'Émettez des ordonnances numériques qui sont acheminées automatiquement vers la pharmacie partenaire la plus proche.',
    m5h:'Analytique & rapports', m5p:'Suivez les consultations, références, revenus et résultats des patients par jour, semaine ou mois.',
    m6h:'Paiements & facturation', m6p:'Klinova gère la facturation des patients et envoie votre part dans les 48 heures suivant chaque consultation.',
    dash_title:'Aperçu de la clinique', dash_ref:'Références aujourd\'hui', dash_rev:'Revenus ce mois', dash_wait:'Attente moy. patient', dash_rx:'Rx en attente',
    rev_ey:'Modèle de revenus', rev_h:'Vous êtes payé. Nous grandissons ensemble.',
    rev_sub:'Les partenaires Klinova gagnent des revenus sur chaque référence et consultation acheminée via la plateforme.',
    r1h:'80%', r1l:'Revenus de consultation aux cliniques', r1p:'Pour chaque visite en clinique générée par une référence Klinova, votre clinique conserve 80% des honoraires de consultation.',
    r2h:'100%', r2l:'Revenus d\'ordonnances aux pharmacies', r2p:'Vous conservez l\'intégralité des revenus d\'ordonnances. Klinova ne perçoit qu\'une petite commission d\'acheminement.',
    r3h:'48h', r3l:'Règlement des paiements', r3p:'Les revenus sont réglés sur votre mobile money ou compte bancaire dans les 48 heures suivant chaque transaction.',
    join_ey:'Comment rejoindre', join_h:'Intégration en trois étapes.',
    j1h:'Postuler en ligne', j1p:'Remplissez le formulaire de partenaire pilote ci-dessous. Indiquez-nous votre type de partenaire, localisation et capacité. Moins de cinq minutes.',
    j2h:'Être vérifié', j2p:'Notre équipe vérifie votre licence, localisation et préparation. Nous répondons généralement sous 3 jours ouvrés.',
    j3h:'Démarrer', j3p:'Vous êtes ajouté au réseau Klinova. Les patients et les références commencent à affluer immédiatement. Votre tableau de bord est en ligne.',
    app_ey:'Programme partenaire pilote', app_h:'Rejoignez notre pilote. Sans frais de configuration.',
    app_p:"Nous développons notre réseau de partenaires au Togo, Ghana, Bénin et en Côte d'Ivoire. Les partenaires pilotes sont intégrés gratuitement et travaillent directement avec notre équipe.",
    b1:'Pas de frais de configuration pour les partenaires pilotes', b2:'Support d\'intégration dédié', b3:'Co-marketing auprès de notre réseau de patients', b4:'Accès anticipé aux nouvelles fonctionnalités', b5:'Influencer la feuille de route produit',
    form_title:'Candidature partenaire', f1:'Nom de l\'organisation', f2:'Type de partenaire', f3:'Pays', f4:'Votre nom', f5:'Email de contact',
    sel_type:'Sélectionner un type…', opt_clinic:'Clinique / Hôpital', opt_pharma:'Pharmacie', opt_doc:'Médecin / Infirmier (individuel)', opt_lab:'Laboratoire / Centre de diagnostic', opt_del:'Livraison / Transport',
    sel_country:'Sélectionner un pays…', opt_other:'Autre',
    submit:'Soumettre la candidature', form_note:'Nous répondons dans les 3 jours ouvrés.',
    ft_blurb:'La grille invisible qui alimente la santé africaine. Lomé, Togo.', ft_tag:'Né en Afrique. Construit pour la Vie.',
    ft_product:'Produit', ft_partners:'Partenaires', ft_company:'Entreprise', ft_copy:'© 2026 Klinova. Tous droits réservés.',
  }
}

export default function PartnersPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [lang, setLang] = useState('en')
  const t = k => T[lang]?.[k] ?? T.en[k]
  useEffect(() => {
    document.body.style.overflow = menuOpen ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [menuOpen])
  return (
    <>
      <style suppressHydrationWarning>{`
        *{box-sizing:border-box;margin:0;padding:0}
        html{scroll-behavior:smooth}
        body{font-family:${ui};color:${C.ink};background:${C.ivory};line-height:1.6;-webkit-font-smoothing:antialiased}
        a{color:inherit;text-decoration:none}
        button{font-family:${ui}}
        .wrap{max-width:1140px;margin:0 auto;padding:0 22px}
        .eyebrow{font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:${C.green}}
        h1{font-family:${display};font-weight:600;font-size:clamp(36px,4.8vw,58px);line-height:1.03;letter-spacing:-.028em;margin:18px 0 0}
        h1 .accent{color:${C.green}}
        h2{font-family:${display};font-weight:600;font-size:clamp(27px,3.4vw,38px);line-height:1.08;letter-spacing:-.02em;margin-top:12px}
        h3{font-family:${display};font-weight:600;font-size:20px;margin-top:0}
        section{padding:80px 0;border-bottom:1px solid ${C.line}}
        .sub{color:#41554C;font-size:16px;margin-top:14px;line-height:1.65}
        .btn{display:inline-flex;align-items:center;gap:8px;border-radius:11px;padding:13px 22px;font-family:${ui};font-weight:700;font-size:14px;cursor:pointer;border:none;transition:transform .14s,box-shadow .14s,background .14s;text-decoration:none}
        .btn:hover{transform:translateY(-1px)}
        .btn-primary{background:${C.green};color:#fff;box-shadow:0 8px 24px -8px rgba(14,107,79,.7)}
        .btn-primary:hover{background:${C.greenDeep}}
        .btn-gold{background:${C.gold};color:#fff;box-shadow:0 8px 24px -8px rgba(217,154,43,.6)}
        .btn-gold:hover{background:${C.amber}}
        .btn-ghost{background:rgba(255,255,255,.7);color:${C.ink};border:1.5px solid ${C.line}}
        .btn-ghost:hover{border-color:${C.green};color:${C.greenDeep};background:#fff}
        /* NAV */
        header{position:sticky;top:0;z-index:100;background:rgba(232,224,208,.95);backdrop-filter:blur(20px) saturate(160%);border-bottom:1px solid rgba(210,200,182,.7)}
        nav{display:flex;align-items:center;justify-content:space-between;gap:6px;height:66px;padding:0 28px;max-width:1200px;margin:0 auto}
        .nav-links{display:flex;align-items:center;gap:2px;flex:1;justify-content:center}
        .nav-links a{font-size:13.5px;font-weight:600;color:${C.mute};padding:7px 12px;border-radius:8px;transition:color .15s,background .15s}
        .nav-links a:hover,.nav-links a.active{color:${C.ink};background:rgba(14,107,79,.07)}
        .nav-links a.active{color:${C.greenDeep}}
        .nav-right{display:flex;align-items:center;gap:8px;flex:none}
        .nav-lang{display:inline-flex;align-items:center}
        .lang-pill{display:inline-flex;align-items:center;background:rgba(14,107,79,.08);border:1px solid rgba(14,107,79,.15);border-radius:999px;overflow:hidden}
        .lp-btn{border:none;background:transparent;font-family:${ui};font-size:12px;font-weight:700;letter-spacing:.06em;color:${C.mute};padding:5px 11px;cursor:pointer;transition:background .15s,color .15s}
        .lp-btn:hover{background:rgba(14,107,79,.10);color:${C.ink}}
        .lp-btn.lp-on{background:${C.green};color:#fff}
        .hamburger{display:flex;background:none;border:none;cursor:pointer;color:${C.ink};padding:6px;border-radius:8px;line-height:0}
        .hamburger:hover{background:rgba(14,107,79,.08)}
        .mob-drawer{display:block;position:fixed;top:0;left:0;width:100vw;height:100vh;z-index:300}
        .mob-nav{position:fixed;top:0;left:0;width:100vw;height:100vh;max-width:none;margin:0;background:${C.greenDeep};display:flex;flex-direction:column;overflow-y:auto;-webkit-overflow-scrolling:touch;z-index:301}
        .mob-close{position:absolute;top:20px;right:24px;background:none;border:none;cursor:pointer;color:rgba(255,255,255,.6);padding:8px;border-radius:8px;line-height:0}
        .mob-close:hover{background:rgba(255,255,255,.1);color:#fff}
        .mob-links{flex:1;display:flex;flex-direction:column;justify-content:center;padding:40px 10vw}
        .mob-links a{font-family:${display};font-size:clamp(28px,4vw,52px);font-weight:600;color:rgba(255,255,255,.82);text-decoration:none;padding:18px 0;border-bottom:1px solid rgba(255,255,255,.1);transition:color .15s,padding-left .18s;display:block}
        .mob-links a:first-child{border-top:1px solid rgba(255,255,255,.1)}
        .mob-links a:hover{color:#fff;padding-left:12px}
        .mob-foot{padding:28px 10vw;border-top:1px solid rgba(255,255,255,.12);display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px}
        .mob-foot-lang{display:flex;gap:8px}
        .mob-foot-lang button{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.2);border-radius:8px;color:rgba(255,255,255,.65);font-family:${ui};font-size:13px;font-weight:700;padding:7px 20px;cursor:pointer;transition:background .15s,color .15s}
        .mob-foot-lang button.active{background:rgba(255,255,255,.18);color:#fff;border-color:rgba(255,255,255,.35)}
        .mob-foot-actions{display:flex;align-items:center;gap:20px}
        .mob-foot-actions a{font-size:15px;font-weight:600;text-decoration:none}
        .mob-foot-login{color:rgba(255,255,255,.6)}
        .mob-foot-cta{color:${C.gold}}
        /* HERO */
        .hero{padding:80px 0 96px;overflow:hidden;position:relative}
        .hero::before{content:'';position:absolute;inset:0;background:radial-gradient(ellipse 80% 60% at 70% 40%,rgba(14,107,79,.07) 0%,transparent 70%);pointer-events:none}
        .hero-inner{max-width:760px}
        .lede{font-size:17px;color:#41554C;margin-top:22px;max-width:55ch;line-height:1.68}
        .cta{display:flex;gap:10px;margin-top:30px;flex-wrap:wrap}
        .trust{display:flex;gap:22px;margin-top:22px;flex-wrap:wrap;font-size:12.5px;color:${C.mute};font-weight:600}
        .trust-item{display:flex;align-items:center;gap:7px}
        .trust-dot{width:5px;height:5px;border-radius:50%;background:${C.gold};flex:none}
        /* PARTNER TYPES */
        .ptype-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:48px}
        .ptype-card{background:${C.card};border:1px solid ${C.line};border-radius:20px;padding:28px 22px;display:flex;flex-direction:column;gap:14px}
        .ptype-icon{width:44px;height:44px;border-radius:12px;background:${C.greenSoft};color:${C.greenDeep};display:grid;place-items:center;flex:none}
        .ptype-card h3{font-size:17px;font-weight:700;font-family:${ui};margin:0}
        .ptype-card p{font-size:14px;color:${C.mute};line-height:1.6;margin:0;flex:1}
        .ptype-tag{display:inline-block;font-size:11px;font-weight:700;padding:4px 10px;border-radius:999px;background:${C.greenSoft};color:${C.greenDeep}}
        /* DASHBOARD MODULES */
        .dash-layout{display:grid;grid-template-columns:1fr 1fr;gap:40px;align-items:start;margin-top:48px}
        .module-list{display:flex;flex-direction:column;gap:12px}
        .mod{background:${C.card};border:1px solid ${C.line};border-radius:16px;padding:20px 18px;display:flex;align-items:flex-start;gap:14px}
        .mod-icon{width:40px;height:40px;border-radius:12px;background:${C.greenSoft};color:${C.greenDeep};display:grid;place-items:center;font-size:18px;flex:none}
        .mod-text h4{font-size:15px;font-weight:700;font-family:${ui};margin:0 0 4px}
        .mod-text p{font-size:13px;color:${C.mute};line-height:1.55;margin:0}
        .dash-preview{background:${C.greenDeep};border-radius:24px;padding:28px;position:sticky;top:90px}
        .dash-preview-title{font-family:${display};font-size:22px;font-weight:600;color:#fff;margin-bottom:18px}
        .dash-stat{display:flex;justify-content:space-between;align-items:center;background:rgba(255,255,255,.08);border-radius:12px;padding:14px 16px;margin-bottom:10px}
        .dash-stat-label{font-size:13px;color:rgba(255,255,255,.6)}
        .dash-stat-val{font-family:${display};font-size:26px;font-weight:600;color:#fff}
        .dash-stat-badge{font-size:11px;font-weight:700;color:${C.gold};background:rgba(217,154,43,.15);padding:3px 8px;border-radius:999px}
        /* HOW TO JOIN */
        .join-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:48px}
        .jstep{background:${C.card};border:1px solid ${C.line};border-radius:20px;padding:28px 24px}
        .jstep-num{font-family:${display};font-size:48px;font-weight:600;color:${C.greenSoft};line-height:1;margin-bottom:12px}
        .jstep h3{font-size:17px;font-weight:700;font-family:${ui};margin:0 0 8px}
        .jstep p{font-size:14px;color:${C.mute};line-height:1.6;margin:0}
        /* REVENUE */
        .rev-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;margin-top:40px}
        .rev-card{background:${C.card};border:1px solid ${C.line};border-radius:20px;padding:28px 22px;display:flex;flex-direction:column;gap:8px}
        .rev-card h3{font-family:${display};font-size:32px;font-weight:600;color:${C.greenDeep}}
        .rev-card-label{font-size:14px;font-weight:700;color:${C.ink}}
        .rev-card p{font-size:13.5px;color:${C.mute};line-height:1.6}
        /* PILOT APPLICATION */
        .pilot{background:${C.sand};border:1px solid ${C.line};border-radius:24px;padding:48px;margin-top:0;display:grid;grid-template-columns:1.2fr .8fr;gap:48px;align-items:center}
        .pilot h2{margin-top:8px}
        .pilot p{margin-top:14px;font-size:15px;color:#41554C;line-height:1.65}
        .pilot-bullets{display:flex;flex-direction:column;gap:8px;margin-top:20px}
        .pilot-bullet{display:flex;align-items:center;gap:10px;font-size:14px;color:${C.ink};font-weight:500}
        .pilot-bullet::before{content:'✓';font-weight:800;color:${C.green};font-size:13px;flex:none}
        .pilot-form{background:${C.card};border-radius:18px;padding:28px;display:flex;flex-direction:column;gap:14px}
        .form-field{display:flex;flex-direction:column;gap:6px}
        .form-label{font-size:12px;font-weight:700;color:${C.mute};letter-spacing:.06em;text-transform:uppercase}
        .form-input{padding:11px 14px;border:1.5px solid ${C.line};border-radius:10px;font-family:${ui};font-size:14px;color:${C.ink};background:#fff;transition:border-color .15s;outline:none}
        .form-input:focus{border-color:${C.green}}
        .form-select{padding:11px 14px;border:1.5px solid ${C.line};border-radius:10px;font-family:${ui};font-size:14px;color:${C.ink};background:#fff;outline:none;cursor:pointer;appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpath d='M1 1l5 5 5-5' stroke='%236E7F76' stroke-width='1.5' fill='none' stroke-linecap='round'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 12px center}
        /* FOOTER */
        footer{background:${C.greenDeep};color:rgba(255,255,255,.7);padding:60px 0 30px}
        .footer-grid{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:40px}
        .footer-logo-name{font-family:${display};font-weight:700;font-size:18px;color:#fff;margin-bottom:10px}
        .footer-blurb{font-size:13.5px;line-height:1.65;max-width:28ch}
        .footer-tagline{font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:${C.gold};margin-top:14px}
        .footer-col-title{font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:rgba(255,255,255,.4);margin-bottom:16px}
        .footer-col a{display:block;font-size:14px;color:rgba(255,255,255,.65);margin-bottom:10px;transition:color .15s}
        .footer-col a:hover{color:#fff}
        .footer-bottom{display:flex;justify-content:space-between;align-items:center;border-top:1px solid rgba(255,255,255,.1);margin-top:48px;padding-top:24px;font-size:12.5px}
        /* ── tablet ─────────────────────────── */
        @media(max-width:1024px){
          .ptype-grid{grid-template-columns:1fr 1fr}
          .rev-grid{grid-template-columns:1fr 1fr}
          .dash-layout{grid-template-columns:1fr}
          .dash-preview{position:static}
          .footer-grid{grid-template-columns:1fr 1fr 1fr}
        }
        /* ── mobile ─────────────────────────── */
        @media(max-width:768px){
          section{padding:56px 0}
          .ptype-grid,.join-steps,.rev-grid,.dash-layout,.pilot{grid-template-columns:1fr}
          .footer-grid{grid-template-columns:1fr 1fr}
          nav{padding:0 14px;height:58px;justify-content:space-between}
          .nav-links{display:none}
          .pilot{padding:28px 20px}
          .dash-preview{position:static}
        }
        /* ── small phone ─────────────────────── */
        @media(max-width:480px){
          section{padding:40px 0}
          .wrap{padding:0 16px}
          .footer-grid{grid-template-columns:1fr}
          h1{font-size:32px}
          h2{font-size:24px}
          .lede{font-size:16px;max-width:none}
          .pilot-form{padding:20px 16px}
          .form-input,.form-select{font-size:16px}
          .footer-col{display:none}
          .footer-grid > div:first-child{display:block}
          .rev-card h3{font-size:28px}
        }
      `}</style>

      <header>
        <nav>
          <a href="/" style={{ display:'flex', alignItems:'center', gap:10, flexShrink:0 }}>
            <img src="/klinova-logo-full.png" alt="Klinova" style={{ height:32, width:'auto', mixBlendMode:'multiply' }} />
          </a>
          <div className="nav-links">
            <a href="/governments">{t('nav_gov')}</a>
            <a href="/patients">{t('nav_ind')}</a>
            <a href="/partner" className="active">{t('nav_par')}</a>
            <a href="mailto:contact@klinova.co">{t('nav_contact')}</a>
          </div>
          <div className="nav-right">
            <button className="hamburger" onClick={() => setMenuOpen(o => !o)} aria-label="Menu">
              {menuOpen
                ? <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
                : <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="3" y1="7" x2="21" y2="7"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="17" x2="21" y2="17"/></svg>
              }
            </button>
          </div>
        </nav>
      </header>

      {menuOpen && (
        <div className="mob-drawer" onClick={() => setMenuOpen(false)}>
          <nav className="mob-nav" onClick={e => e.stopPropagation()}>
            <button className="mob-close" onClick={() => setMenuOpen(false)} aria-label="Close menu">
              <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
            </button>
            <div className="mob-links">
              <a href="/governments" onClick={() => setMenuOpen(false)}>{t('nav_gov')}</a>
              <a href="/patients" onClick={() => setMenuOpen(false)}>{t('nav_ind')}</a>
              <a href="/partner" onClick={() => setMenuOpen(false)}>{t('nav_par')}</a>
            </div>
            <div className="mob-foot">
              <div className="mob-foot-lang">
                <button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button>
                <button className={lang==='fr'?'active':''} onClick={()=>setLang('fr')}>FR</button>
              </div>
              <div className="mob-foot-actions">
                <a href="/login" className="mob-foot-login" onClick={() => setMenuOpen(false)}>{t('nav_login')}</a>
                <a href="mailto:contact@klinova.co?subject=Partner Application" className="mob-foot-cta" onClick={() => setMenuOpen(false)}>{t('nav_cta')} →</a>
              </div>
            </div>
          </nav>
        </div>
      )}

      {/* HERO */}
      <section className="hero" style={{ borderBottom:'none' }}>
        <div className="wrap">
          <div className="hero-inner">
            <div className="eyebrow">{t('eyebrow')}</div>
            <h1>{t('h1')}<span className="accent">{t('h1_accent')}</span></h1>
            <p className="lede">{t('lede')}</p>
            <div className="cta">
              <a href="#apply" className="btn btn-primary">{t('cta1')}</a>
              <a href="mailto:contact@klinova.co" className="btn btn-ghost">{t('cta2')}</a>
            </div>
            <div className="trust">
              <span className="trust-item"><span className="trust-dot"/><span>{t('tr1')}</span></span>
              <span className="trust-item"><span className="trust-dot"/><span>{t('tr2')}</span></span>
              <span className="trust-item"><span className="trust-dot"/><span>{t('tr3')}</span></span>
            </div>
          </div>
        </div>
      </section>

      {/* PARTNER TYPES */}
      <section id="clinics">
        <div className="wrap">
          <div className="eyebrow">{t('pt_ey')}</div>
          <h2>{t('pt_h')}</h2>
          <div className="ptype-grid">
            <div className="ptype-card">
              <div className="ptype-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 21h18M3 10h18M3 7l9-4 9 4M4 10v11M20 10v11M8 14v3M12 14v3M16 14v3"/></svg></div>
              <h3>{t('p1h')}</h3>
              <p>{t('p1p')}</p>
              <span className="ptype-tag">{t('p1t')}</span>
            </div>
            <div className="ptype-card" id="pharmacies">
              <div className="ptype-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M9 3h6M9 3v8L4.5 19a1 1 0 0 0 .9 1.5h13.2a1 1 0 0 0 .9-1.5L15 11V3"/><path d="M6 14h12"/></svg></div>
              <h3>{t('p2h')}</h3>
              <p>{t('p2p')}</p>
              <span className="ptype-tag">{t('p2t')}</span>
            </div>
            <div className="ptype-card" id="doctors">
              <div className="ptype-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></div>
              <h3>{t('p3h')}</h3>
              <p>{t('p3p')}</p>
              <span className="ptype-tag">{t('p3t')}</span>
            </div>
            <div className="ptype-card">
              <div className="ptype-icon"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M5 17H3a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v3"/><rect x="9" y="11" width="14" height="10" rx="1"/><path d="M16 11V7"/><circle cx="12" cy="16" r="1"/></svg></div>
              <h3>{t('p4h')}</h3>
              <p>{t('p4p')}</p>
              <span className="ptype-tag">{t('p4t')}</span>
            </div>
          </div>
        </div>
      </section>

      {/* CLINIC DASHBOARD */}
      <section>
        <div className="wrap">
          <div className="eyebrow">{t('dash_ey')}</div>
          <h2>{t('dash_h')}</h2>
          <p className="sub">{t('dash_sub')}</p>
          <div className="dash-layout">
            <div className="module-list">
              {[
                { ico:<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>, hk:'m1h', pk:'m1p' },
                { ico:<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>, hk:'m2h', pk:'m2p' },
                { ico:<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M16 13H8M16 17H8M10 9H8"/></svg>, hk:'m3h', pk:'m3p' },
                { ico:<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M9 3h6M9 3v8L4.5 19a1 1 0 0 0 .9 1.5h13.2a1 1 0 0 0 .9-1.5L15 11V3"/><path d="M6 14h12"/></svg>, hk:'m4h', pk:'m4p' },
                { ico:<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 3v18h18"/><path d="M7 16v-5M11 16V8M15 16v-3M19 16V5"/></svg>, hk:'m5h', pk:'m5p' },
                { ico:<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><rect x="1" y="4" width="22" height="16" rx="2"/><path d="M1 10h22"/></svg>, hk:'m6h', pk:'m6p' },
              ].map(m => (
                <div className="mod" key={m.hk}>
                  <div className="mod-icon">{m.ico}</div>
                  <div className="mod-text">
                    <h4>{t(m.hk)}</h4>
                    <p>{t(m.pk)}</p>
                  </div>
                </div>
              ))}
            </div>
            <div className="dash-preview">
              <div className="dash-preview-title">{t('dash_title')}</div>
              <div className="dash-stat">
                <div>
                  <div className="dash-stat-label">{t('dash_ref')}</div>
                  <div className="dash-stat-val">14</div>
                </div>
                <div className="dash-stat-badge">+3 new</div>
              </div>
              <div className="dash-stat">
                <div>
                  <div className="dash-stat-label">{t('dash_rev')}</div>
                  <div className="dash-stat-val">287k XOF</div>
                </div>
                <div className="dash-stat-badge">↑ 22%</div>
              </div>
              <div className="dash-stat">
                <div>
                  <div className="dash-stat-label">{t('dash_wait')}</div>
                  <div className="dash-stat-val">12 min</div>
                </div>
                <div className="dash-stat-badge">↓ 8 min</div>
              </div>
              <div style={{ marginTop:18, padding:'14px 16px', background:'rgba(255,255,255,.06)', borderRadius:12 }}>
                <div style={{ fontSize:12, color:'rgba(255,255,255,.5)', marginBottom:8, fontWeight:700, letterSpacing:'.06em', textTransform:'uppercase' }}>{t('dash_rx')}</div>
                {['Amina K. – Amoxicillin 500mg','Kodjo M. – Metformin 850mg','Abena A. – Ibuprofen 400mg'].map(r => (
                  <div key={r} style={{ display:'flex', alignItems:'center', gap:8, fontSize:13, color:'rgba(255,255,255,.75)', padding:'7px 0', borderBottom:'1px solid rgba(255,255,255,.08)' }}>
                    <span style={{ width:6, height:6, borderRadius:'50%', background:C.gold, flexShrink:0 }}/>
                    {r}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* REVENUE */}
      <section>
        <div className="wrap">
          <div className="eyebrow">{t('rev_ey')}</div>
          <h2>{t('rev_h')}</h2>
          <p className="sub">{t('rev_sub')}</p>
          <div className="rev-grid">
            <div className="rev-card">
              <h3>{t('r1h')}</h3>
              <div className="rev-card-label">{t('r1l')}</div>
              <p>{t('r1p')}</p>
            </div>
            <div className="rev-card">
              <h3>{t('r2h')}</h3>
              <div className="rev-card-label">{t('r2l')}</div>
              <p>{t('r2p')}</p>
            </div>
            <div className="rev-card">
              <h3>{t('r3h')}</h3>
              <div className="rev-card-label">{t('r3l')}</div>
              <p>{t('r3p')}</p>
            </div>
          </div>
        </div>
      </section>

      {/* HOW TO JOIN */}
      <section>
        <div className="wrap">
          <div className="eyebrow">{t('join_ey')}</div>
          <h2>{t('join_h')}</h2>
          <div className="join-steps">
            <div className="jstep">
              <div className="jstep-num">01</div>
              <h3>{t('j1h')}</h3>
              <p>{t('j1p')}</p>
            </div>
            <div className="jstep">
              <div className="jstep-num">02</div>
              <h3>{t('j2h')}</h3>
              <p>{t('j2p')}</p>
            </div>
            <div className="jstep">
              <div className="jstep-num">03</div>
              <h3>{t('j3h')}</h3>
              <p>{t('j3p')}</p>
            </div>
          </div>
        </div>
      </section>

      {/* PILOT APPLICATION FORM */}
      <section id="apply">
        <div className="wrap">
          <div className="pilot">
            <div>
              <div className="eyebrow">{t('app_ey')}</div>
              <h2>{t('app_h')}</h2>
              <p>{t('app_p')}</p>
              <div className="pilot-bullets">
                <div className="pilot-bullet">{t('b1')}</div>
                <div className="pilot-bullet">{t('b2')}</div>
                <div className="pilot-bullet">{t('b3')}</div>
                <div className="pilot-bullet">{t('b4')}</div>
                <div className="pilot-bullet">{t('b5')}</div>
              </div>
            </div>
            <div className="pilot-form">
              <div style={{ fontFamily:display, fontWeight:600, fontSize:18, color:C.ink, marginBottom:4 }}>{t('form_title')}</div>
              <div className="form-field">
                <label className="form-label">{t('f1')}</label>
                <input className="form-input" type="text" placeholder="Clinique Espoir" />
              </div>
              <div className="form-field">
                <label className="form-label">{t('f2')}</label>
                <select className="form-select">
                  <option value="">{t('sel_type')}</option>
                  <option>{t('opt_clinic')}</option>
                  <option>{t('opt_pharma')}</option>
                  <option>{t('opt_doc')}</option>
                  <option>{t('opt_lab')}</option>
                  <option>{t('opt_del')}</option>
                </select>
              </div>
              <div className="form-field">
                <label className="form-label">{t('f3')}</label>
                <select className="form-select">
                  <option value="">{t('sel_country')}</option>
                  <option>Togo</option>
                  <option>Ghana</option>
                  <option>Benin</option>
                  <option>Côte d'Ivoire</option>
                  <option>{t('opt_other')}</option>
                </select>
              </div>
              <div className="form-field">
                <label className="form-label">{t('f4')}</label>
                <input className="form-input" type="text" placeholder="Dr. Abena Mensah" />
              </div>
              <div className="form-field">
                <label className="form-label">{t('f5')}</label>
                <input className="form-input" type="email" placeholder="you@yourclinic.com" />
              </div>
              <a href="mailto:contact@klinova.co?subject=Partner Application" className="btn btn-primary" style={{ justifyContent:'center', marginTop:4 }}>
                {t('submit')}
              </a>
              <p style={{ fontSize:12, color:C.mute, textAlign:'center' }}>{t('form_note')}</p>
            </div>
          </div>
        </div>
      </section>

      <footer>
        <div className="wrap">
          <div className="footer-grid">
            <div>
              <div className="footer-logo-name">KLINOVA</div>
              <div className="footer-blurb">{t('ft_blurb')}</div>
              <div className="footer-tagline">{t('ft_tag')}</div>
            </div>
            <div>
              <div className="footer-col-title">{t('ft_product')}</div>
              <div className="footer-col">
                <a href="/patients">For patients</a>
                <a href="/partner">For partners</a>
                <a href="/governments">For governments</a>
                <a href="/#pricing">Pricing</a>
              </div>
            </div>
            <div>
              <div className="footer-col-title">{t('ft_partners')}</div>
              <div className="footer-col">
                <a href="/partner#clinics">Clinics</a>
                <a href="/partner#pharmacies">Pharmacies</a>
                <a href="/partner#doctors">Doctors</a>
                <a href="/governments">Governments</a>
              </div>
            </div>
            <div>
              <div className="footer-col-title">{t('ft_company')}</div>
              <div className="footer-col">
                <a href="mailto:contact@klinova.co">Contact</a>
                <a href="/privacy">Privacy and data</a>
              </div>
            </div>
          </div>
          <div className="footer-bottom">
            <span>{t('ft_copy')}</span>
            <a href="https://kinaraos.com" target="_blank" rel="noopener noreferrer" style={{ color: '#5A7A6E', textDecoration: 'none' }}>
              {lang === 'fr' ? 'Klinova · Alimenté par Kinara OS' : 'Klinova · Powered by Kinara OS'}
            </a>
          </div>
        </div>
      </footer>
    </>
  )
}
