-- Global health outbreaks (sourced from WHO + ReliefWeb)
CREATE TABLE IF NOT EXISTS health_outbreaks (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now(),
  source       text DEFAULT 'WHO',
  source_url   text UNIQUE,
  disease      text NOT NULL,
  location_name text,
  location_lat  double precision,
  location_lng  double precision,
  severity     text DEFAULT 'warning' CHECK (severity IN ('info','warning','critical')),
  summary      text,
  detected_at  timestamptz DEFAULT now(),
  active       boolean DEFAULT true
);

-- Advisories generated by AI, approved by owner
CREATE TABLE IF NOT EXISTS health_advisories (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at   timestamptz DEFAULT now(),
  outbreak_id  uuid REFERENCES health_outbreaks(id) ON DELETE SET NULL,
  title        text NOT NULL,
  body_en      text,
  body_fr      text,
  body_local   text,
  severity     text DEFAULT 'warning' CHECK (severity IN ('info','warning','critical')),
  status       text DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
  published_by uuid REFERENCES users(id),
  published_at timestamptz
);

ALTER TABLE health_outbreaks  ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_advisories ENABLE ROW LEVEL SECURITY;

-- Any authenticated user can read (doctors, pharmacists, government, etc.)
CREATE POLICY "read_outbreaks"   ON health_outbreaks  FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "read_advisories"  ON health_advisories FOR SELECT USING (auth.uid() IS NOT NULL);

-- Only service role can insert/update outbreaks (done by cron/API route)
-- Advisories: owner/admin can update status
CREATE POLICY "owner_update_advisories"
  ON health_advisories FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('owner','admin')
    )
  );
